# Generated by Django 2.1.2 on 2018-10-19 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('text', models.TextField(blank=True, null=True, verbose_name='message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'messages',
                'verbose_name': 'message',
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='time created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='time modified')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-created',),
                'verbose_name_plural': 'threads',
                'verbose_name': 'thread',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dialogs.Thread', verbose_name='thread'),
        ),
    ]
